### ISSUE TITLE
Installing signed packages failes.

### ISSUE THREAD

**Issue by berhoel** [conao3/feather.el#3]
Trying to install signed packages like `sql-indent`or `queue` using feather failes with an error regarding checking the signature.

**Comment by conao3** [comment]
![Screenshot_2020-03-24_01-00-04](https://user-images.githubusercontent.com/4703128/77336922-8cd63c00-6d6b-11ea-951c-ec1d018e8708.png)

This issue is reproducible using clean Emacs?
I used below init.el and invoke Emacs with `emacs -q -l ~/.debug.emacs.d/feather/init.el` and do `M-x list-package`, some package installing are completed with no warnings/errors.

```elisp
;; ~/.debug.emacs.d/feather/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/{{pkg}}/init.el'
(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(prog1 "prepare leaf"
  (prog1 "package"
    (custom-set-variables
     '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                          ("melpa" . "https://melpa.org/packages/")
                          ("gnu"   . "https://elpa.gnu.org/packages/"))))
    (package-initialize))

  (prog1 "leaf"
    (unless (package-installed-p 'leaf)
      (package-refresh-contents)
      (package-install 'leaf))))



(leaf feather
  :ensure t
  :global-minor-mode feather-mode)
```

**Comment by berhoel** [comment]
It is not reproducible in a clean Emacs, it is not even reproducible in my Emacs environment under OpenSuse Tumbleweed, but it occurred under a broken WSL based Ubuntu, so I guess the currently broken libc on this system is the culprit.

**Comment by mgttlinger** [comment]
Are there any hints for how to narrow down what breaks that signature check in my "non-clean" emacs version?
